apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-agri
resources:
  - namespace.yaml
  - config.yaml
  - discovery-service.yaml
  - api-gateway.yaml
  - backend-services.yaml
