server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/auth_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

app:
  jwt:
    secret: 926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
