apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/veejvn/smart-agri-system/api-gateway
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/auth-service
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/user-service
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/crop-service
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/weather-service
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/forum-service
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/notification-service
    newTag: staging
  - name: ghcr.io/veejvn/smart-agri-system/discovery-service
    newTag: staging
replicas:
  - name: api-gateway
    count: 2
  - name: auth-service
    count: 2
